#![recursion_limit = "256"]

pub mod app;
pub mod discovery;
pub mod schema;
mod size_estimation;
pub mod transport;
mod views;

#[cfg(not(target_arch = "wasm32"))]
extern crate hiroz_cdr_native as hiroz_cdr;
#[cfg(target_arch = "wasm32")]
extern crate hiroz_cdr_wasm as hiroz_cdr;
#[cfg(not(target_arch = "wasm32"))]
extern crate hiroz_native as hiroz;
#[cfg(not(target_arch = "wasm32"))]
extern crate hiroz_protocol_native as protocol;
#[cfg(target_arch = "wasm32")]
extern crate hiroz_protocol_wasm as protocol;
#[cfg(target_arch = "wasm32")]
extern crate hiroz_wasm as hiroz;

pub mod messages {
    #![allow(clippy::all, dead_code, unexpected_cfgs)]
    include!(concat!(env!("OUT_DIR"), "/generated.rs"));
}

// Custom-message crates generated by hiroz-codegen can use this crate as the
// source of their standard ROS dependencies.
pub use messages::ros;
pub use schema::Registry as TypeRegistry;

#[cfg(not(target_arch = "wasm32"))]
use clap::Parser;

#[cfg(not(target_arch = "wasm32"))]
#[derive(Parser)]
#[command(
    version,
    about = "Discover ROS domains and inspect topics through a Zenoh router"
)]
struct Cli {
    /// Connect to this Zenoh router at startup (e.g. tcp/rover:7447).
    #[arg(long)]
    endpoint: Option<String>,
    /// Initially filter to this domain; discovery still includes all domains.
    #[arg(long, alias = "domain")]
    domain_id: Option<usize>,
}

/// Run the native inspector with its built-in ROS interface definitions.
#[cfg(not(target_arch = "wasm32"))]
pub fn run() -> eframe::Result {
    run_with_custom_types(schema::Registry::new())
}

/// Run the native inspector after merging deployment-specific message schemas
/// into its built-in registry.
#[cfg(not(target_arch = "wasm32"))]
pub fn run_with_custom_types(custom_types: schema::Registry) -> eframe::Result {
    let cli = Cli::parse();
    eframe::run_native(
        "Inspector / Zenoh",
        eframe::NativeOptions {
            viewport: egui::ViewportBuilder::default()
                .with_inner_size([1200.0, 800.0])
                .with_min_inner_size([720.0, 480.0]),
            ..Default::default()
        },
        Box::new(move |cc| {
            Ok(Box::new(app::Inspector::with_custom_types(
                cc,
                cli.endpoint,
                cli.domain_id,
                custom_types,
            )))
        }),
    )
}

#[cfg(target_arch = "wasm32")]
pub async fn start(
    canvas: web_sys::HtmlCanvasElement,
    shim_url: &str,
) -> Result<(), wasm_bindgen::JsValue> {
    start_with_custom_types(canvas, shim_url, schema::Registry::new()).await
}

/// Start the browser inspector after merging deployment-specific message
/// schemas into its built-in registry.
#[cfg(target_arch = "wasm32")]
pub async fn start_with_custom_types(
    canvas: web_sys::HtmlCanvasElement,
    shim_url: &str,
    custom_types: schema::Registry,
) -> Result<(), wasm_bindgen::JsValue> {
    console_error_panic_hook::set_once();
    if !zenoh_runtime::__zenoh_init_threaded_runtime(shim_url) {
        return Err(wasm_bindgen::JsValue::from_str(
            "WASM threads require a secure context and COOP/COEP headers. Use web/serve.py on localhost.",
        ));
    }
    eframe::WebRunner::new()
        .start(
            canvas,
            eframe::WebOptions::default(),
            Box::new(move |cc| {
                Ok(Box::new(app::Inspector::new_with_custom_types(
                    cc,
                    custom_types,
                )))
            }),
        )
        .await
}

#[cfg(all(test, not(target_arch = "wasm32")))]
mod tests {
    use super::*;

    #[test]
    fn endpoint_and_domain_arguments() {
        let cli = Cli::try_parse_from([
            "inspector",
            "--endpoint",
            "tcp/rover:7447",
            "--domain-id",
            "42",
        ])
        .unwrap();
        assert_eq!(cli.endpoint.as_deref(), Some("tcp/rover:7447"));
        assert_eq!(cli.domain_id, Some(42));
        let cli = Cli::try_parse_from(["inspector", "--endpoint=ws/localhost:7448"]).unwrap();
        assert_eq!(cli.endpoint.as_deref(), Some("ws/localhost:7448"));
        assert!(cli.domain_id.is_none());
        assert!(Cli::try_parse_from(["inspector", "--endpoint"]).is_err());
        assert!(Cli::try_parse_from(["inspector", "--domain-id", "oops"]).is_err());
        assert!(
            Cli::try_parse_from(["inspector"])
                .unwrap()
                .endpoint
                .is_none()
        );
    }
}
